id = "mcbopomofo-data"
name = "McBopomofo Data"
version = "0.1.0"
schema_version = 1
authors = ["Weizhong Yang <zonble@gmail.com>"]
description = "Syntax highlighting for McBopomofo data files."

[grammars.mcbopomofo_data]
repository = "https://github.com/openvanilla/mcbopomofo-zed-extension"
rev = "9ca478f9bf5eb4aaecb0bae9f19bdafddd36caf8"
