id = "mcbopomofo-data"
name = "McBopomofo Data"
version = "0.1.0"
schema_version = 1
authors = ["Zonble <zonble@gmail.com>"]
description = "Syntax highlighting for McBopomofo data files."

[grammars.mcbopomofo_data]
repository = "file:///Users/zonble/Work/mcbopomofo-zed-extension"
rev = "40087e30dddb91214688869ed367e329783a2595"
